# Generated by Django 6.0 on 2025-12-25 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='langue_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_langue', models.CharField(max_length=200)),
                ('abv_langue', models.CharField(max_length=20)),
                ('langue_card', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rarete_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_rarete', models.CharField(blank=True, max_length=50)),
                ('abv_rarete', models.CharField(blank=True, max_length=10)),
                ('group_rarete', models.CharField(blank=True, max_length=10)),
                ('family_rarete', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ygo_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_card', models.CharField(max_length=50)),
                ('alpha_card', models.CharField(max_length=50)),
                ('level_card', models.CharField(max_length=50)),
                ('nbr_link', models.CharField(max_length=50)),
                ('cross_link', models.CharField(max_length=50)),
                ('artwork_card', models.CharField(blank=True, max_length=50, null=True)),
                ('code_card', models.CharField(max_length=50)),
                ('attack_card', models.CharField(max_length=50)),
                ('defense_card', models.CharField(max_length=50)),
                ('passcode_card', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ygo_extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_extension', models.CharField(max_length=20, unique=True)),
                ('name_extension', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card_Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_translate', models.CharField(max_length=255)),
                ('type_card', models.CharField(blank=True, max_length=100)),
                ('name_card', models.CharField(max_length=255)),
                ('attribut_card', models.CharField(blank=True, max_length=50)),
                ('family_card', models.CharField(blank=True, max_length=100)),
                ('sous_family', models.CharField(blank=True, max_length=100)),
                ('nature_card', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('abv_langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugioh.langue_card')),
                ('base_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugioh.ygo_base')),
            ],
            options={
                'unique_together': {('base_card', 'abv_langue')},
            },
        ),
        migrations.CreateModel(
            name='Classeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('extension_cible', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rarete_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yugioh.rarete_card')),
            ],
        ),
        migrations.CreateModel(
            name='Card_Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_version', models.CharField(blank=True, max_length=255, null=True)),
                ('artwork_card', models.CharField(blank=True, max_length=255, null=True)),
                ('img_card', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('abv_rarete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugioh.rarete_card')),
                ('base_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugioh.ygo_base')),
            ],
            options={
                'unique_together': {('base_card', 'abv_rarete')},
            },
        ),
        migrations.CreateModel(
            name='Rarete_Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarities_translate', models.CharField(blank=True, max_length=100)),
                ('name_rarities', models.CharField(blank=True, max_length=100)),
                ('abv_langue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='yugioh.langue_card')),
                ('abv_rarete', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='yugioh.rarete_card')),
            ],
            options={
                'unique_together': {('abv_rarete', 'abv_langue')},
            },
        ),
        migrations.CreateModel(
            name='Catalogue_Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('card_translate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugioh.card_translation')),
                ('card_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugioh.card_printing')),
                ('rarities_translate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yugioh.rarete_translation')),
            ],
            options={
                'ordering': ['reference', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ygo_base',
            name='extension',
            field=models.ForeignKey(db_column='code_extension', on_delete=django.db.models.deletion.CASCADE, to='yugioh.ygo_extension', to_field='code_extension'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('card_printing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugioh.card_printing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'card_printing')},
            },
        ),
    ]
