# Generated by Django 6.0 on 2025-12-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classeur',
            name='nom_carte_cible',
            field=models.CharField(blank=True, help_text='Ex: Magicien Sombre', max_length=255, null=True),
        ),
    ]
