# Generated by Django 6.0 on 2025-12-27 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh', '0002_classeur_nom_carte_cible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_translation',
            name='base_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='yugioh.ygo_base'),
        ),
    ]
