# Generated by Django 6.0 on 2026-02-10 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballCard',
            fields=[
                ('id_card', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date_sold', models.CharField(blank=True, max_length=100, null=True)),
                ('marque', models.CharField(blank=True, max_length=255, null=True)),
                ('licence', models.CharField(blank=True, max_length=50, null=True)),
                ('produit', models.CharField(blank=True, max_length=50, null=True)),
                ('saison', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name_2', models.CharField(blank=True, max_length=255, null=True)),
                ('name_3', models.CharField(blank=True, max_length=255, null=True)),
                ('name_4', models.CharField(blank=True, max_length=255, null=True)),
                ('name_5', models.CharField(blank=True, max_length=255, null=True)),
                ('name_6', models.CharField(blank=True, max_length=255, null=True)),
                ('name_7', models.CharField(blank=True, max_length=255, null=True)),
                ('name_8', models.CharField(blank=True, max_length=255, null=True)),
                ('name_9', models.CharField(blank=True, max_length=255, null=True)),
                ('name_10', models.CharField(blank=True, max_length=255, null=True)),
                ('name_11', models.CharField(blank=True, max_length=255, null=True)),
                ('name_12', models.CharField(blank=True, max_length=255, null=True)),
                ('teams', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('teams_2', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_3', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_4', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_5', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_6', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_7', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_8', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_9', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_10', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_11', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_12', models.CharField(blank=True, max_length=255, null=True)),
                ('rc', models.CharField(blank=True, db_column='RC', max_length=100, null=True)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('type_card', models.CharField(blank=True, max_length=100, null=True)),
                ('parrallel', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_card', models.CharField(blank=True, max_length=100, null=True)),
                ('numerotation_card', models.CharField(blank=True, max_length=100, null=True)),
                ('type_img', models.CharField(blank=True, max_length=100, null=True)),
                ('recto_img', models.CharField(blank=True, max_length=255, null=True)),
                ('verso_img', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasketCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.basketballcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='bi-star-fill', max_length=50)),
                ('players', models.JSONField(blank=True, default=list)),
                ('teams', models.JSONField(blank=True, default=list)),
                ('seasons', models.JSONField(blank=True, default=list)),
                ('products', models.JSONField(blank=True, default=list)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('types', models.JSONField(blank=True, default=list)),
                ('parallels', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
