# Generated by Django 6.0 on 2026-02-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketballcard',
            name='name_2',
        ),
        migrations.AlterField(
            model_name='basketballcard',
            name='id_card',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
