# Generated by Django 6.0 on 2026-02-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0002_remove_basketballcard_name_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketballcard',
            name='name_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
