# Generated by Django 6.0 on 2026-02-12 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0004_binder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='binder',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='binder',
            name='shelf_number',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ShelfConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_sizes', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
