# Generated by Django 6.0 on 2026-02-13 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0006_librarysettings_delete_shelfconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binder',
            name='cover_color',
        ),
        migrations.RemoveField(
            model_name='binder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='binder',
            name='shelf_number',
        ),
        migrations.AlterField(
            model_name='binder',
            name='format_size',
            field=models.CharField(default='3x3', max_length=20),
        ),
        migrations.AlterField(
            model_name='librarysettings',
            name='shelf_sizes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='librarysettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basketball_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField()),
                ('binder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='basketball.binder')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.basketballcard')),
            ],
            options={
                'unique_together': {('binder', 'slot_number')},
            },
        ),
    ]
