# Generated by Django 6.0 on 2026-02-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0007_remove_binder_cover_color_remove_binder_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binder',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='binder',
            name='shelf_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
