# Generated by Django 6.0 on 2026-02-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0008_binder_order_binder_shelf_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binder',
            name='created_at',
        ),
        migrations.AddField(
            model_name='binder',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='binder',
            name='color',
            field=models.CharField(default='#d32f2f', max_length=7),
        ),
        migrations.AddField(
            model_name='binder',
            name='label_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='binder',
            name='storage_type',
            field=models.CharField(choices=[('small', 'Petit Classeur (2x2)'), ('medium', 'Classeur Standard (3x3)'), ('large', 'Grand Portfolio (4x4)'), ('extra', 'Méga Album (6x5)')], default='medium', max_length=20),
        ),
    ]
