# Generated by Django 6.0 on 2026-02-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0009_remove_binder_created_at_binder_abbreviation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binder',
            name='column_position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
