# Generated by Django 6.0 on 2026-02-22 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0010_binder_column_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='librarysettings',
            name='has_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='librarysettings',
            name='shelf_count',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='librarysettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basketball_library_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ma Bibliothèque', max_length=100)),
                ('position', models.PositiveIntegerField(default=1)),
                ('shelf_sizes', models.JSONField(default=dict)),
                ('shelf_count', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
