# Generated by Django 6.0 on 2026-02-22 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0011_librarysettings_has_library_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='has_library',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='shelf_count',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='library',
            name='shelf_sizes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='library',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball_libraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LibrarySettings',
        ),
    ]
