# Generated by Django 6.0 on 2026-02-22 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0012_library_has_library_alter_library_shelf_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binder',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='binders', to='basketball.library'),
        ),
    ]
